Fixed clear-app-data exception
calabash/iOSDeviceManager pull request #288
Opened 2022-06-29 06:46 UTC by IlyaBausovAkvelon

In this fix:
- Updated idb version to 1.1.7 and fixed issues after that.
- Fixed uncatched clear-app-data exception with that.
- Added Integration and Unit tests to cover clear-app-data command.

2022-07-11 19:09 UTC, AlexeyBudynkov commented
At this moment these command doesn't work on M1:
```
$ make unit-tests
$ make integration-tests
```

_Testing failed:
	The linked and embedded framework 'CocoaLumberjack.framework' is missing one or more architectures required by this target: arm64.
	The linked and embedded framework 'OCMock.framework' is missing one or more architectures required by this target: arm64.
	The linked and embedded framework 'Specta.framework' is missing one or more architectures required by this target: arm64.
	The linked and embedded framework 'Expecta.framework' is missing one or more architectures required by this target: arm64.
	The linked and embedded framework 'CocoaLumberjack.framework' is missing one or more architectures required by this target: arm64.
	Testing cancelled because the build failed._

This command creates other error:
`$ make cli-tests`

_An error occurred while loading ./spec/upload_xctestconfig_spec.rb.
Failure/Error: if RunLoop::Version.new(xcode_version) >= min_xcode_version_

_NoMethodError:
  undefined method `strip' for nil:NilClass_

2022-07-11 19:13 UTC, AlexeyBudynkov commented on iOSDeviceManager/Devices/PhysicalDevice.m
> +        if ([[error localizedDescription] containsString:@"is not installed."]) {
What if we'll have [error localizedDescription] result in other language than English?

2022-07-18 11:43 UTC, AlexeyBudynkov commented on iOSDeviceManager/Utilities/DeviceUtils.m
> +    NSUInteger minor = XcodeUtils.versionMinor+1;
I'm not sure about this workaround.

2022-07-26 08:21 UTC, MatkovIvan requested changes

2022-07-26 08:21 UTC, MatkovIvan commented on IDMLogger.h
> +//
I do not think that it should be placed at the root of repo

2022-07-26 08:21 UTC, MatkovIvan commented on IDMLogger.m
> +//
Same

2022-07-26 08:21 UTC, MatkovIvan commented on IDMLogger.m
> +    case DDLogFlagWarning  : logLevel = @" WARN"; break;
Extra space in string

2022-07-26 08:21 UTC, MatkovIvan commented on iOSDeviceManager/Devices/Simulator.m
> +};
```suggestion
}
```

2022-07-26 08:30 UTC, IlyaBausovAkvelon commented on iOSDeviceManager/Devices/PhysicalDevice.m
> +        if ([[error localizedDescription] containsString:@"is not installed."]) {
Fixed.

2022-07-26 12:17 UTC, MatkovIvan approved these changes

2022-07-27 06:11 UTC, merged